---
- name: Install Application
  hosts: apiservers
  tasks:
    - name: Create Directory Binaries
      file:
        path: "{{ appli_dir }}/bin"
        state: directory
        owner: "{{ appli_user }}"
        group: "{{ appli_group }}"
        mode: "{{ appli_dir_exe_mode }}"
    - name: Create Directory Logs
      file:
        path: "{{ appli_dir }}/log"
        state: directory
        owner: "{{ appli_user }}"
        group: "{{ appli_group }}"
        mode: "{{ appli_dir_exe_mode }}"
    - name: Create link with this version
      file:
        path: /opt/application/latest
        src: "{{ appli_dir }}"
        state: link
        owner: "{{ appli_user }}"
        group: "{{ appli_group }}"
    - name: Copy appli artifact
      copy:
        src: repo_artifacts/appli
        dest: "{{ appli_dir }}/bin"
        owner: "{{ appli_user }}"
        group: "{{ appli_group }}"
        mode: "{{ appli_dir_exe_mode }}"
    - name: Java Toolkit Stack
      apt:
        name: openjdk-11-jdk
        state: present 
  become: yes
  become_method: sudo

- name: DB Installation
  hosts: dbservers
  tasks:
    - name: DB Install, Start
      block:
        - name: DB Server
          apt:
            name: "{{ db_package}}"
            state: present
        - name: Start DB Auto
          systemd:
            name: "{{ db_service }}"
            state: started
            enabled: yes
      become: yes
      become_method: sudo







