---
- name: Install Application
  hosts: apiservers
  roles:
    - common
    - api 
  tags:
    - api
  become: yes
  become_method: sudo


- name: DB Installation
  hosts: dbservers
  roles:
    - common
    - db
  tags:
    - db
  become: yes
  become_method: sudo


- name: Learn
  hosts: apiservers
  roles:
    - learn
  tags:
    - learn
