---
- name: Install Application
  hosts: apiservers
  tasks:
    - name: Create Directory Binaries
      file:
        path: /opt/application/v1/bin
        state: directory
        owner: kali
        group: kali
        mode: 0750
    - name: Create Directory Logs
      file:
        path: /opt/application/v1/log
        state: directory
        owner: kali
        group: kali
        mode: 0750
    - name: Create link with this version
      file:
        path: /opt/application/latest
        src: /opt/application/v1
        state: link
        owner: kali
        group: kali
    - name: Copy appli artifact
      copy:
        src: repo_artifacts/appli
        dest: /opt/application/v1/bin
        owner: kali
        group: kali
        mode: 0750
    - name: Java Toolkit Stack
      apt:
        name: openjdk-11-jdk
        state: present 
  become: yes
  become_method: sudo

- name: DB Installation
  hosts: dbservers
  tasks:
    - name: DB Server
      apt:
        name: postgresql-14
        state: present
      become: yes
      become_method: sudo
    - name: Start DB Auto
      systemd:
        name: postgresql
        state: started
        enabled: yes
      become: yes
      become_method: sudo







