---
# handler with name equals to event
#- name: db check
#  debug:
#    msg: "Check DB"

- name: check 1
  debug:
    msg: "Check DB 1"
  listen: db check


- name: check 2
  #include_tasks: tasks/db_check.yml
  include_tasks: tasks/db_check_pg.yml
  listen: db check

#TODO: check conditional with db vendor: postgresql, mariadb, ...
